numero = int(input('Digite um numero:'))
raiz = numero **(1/2)
print(f'O dobro de {numero} vale {numero*2}')
print(f'o triplo de {numero} vale {numero*3}')
print(f'a raiz quadrada de {numero} é {raiz:.2f}')